build: Add dependency on proto_generated_headers for proto_generated_objects
In case of high j value to make, occasionally headers
required to compile the proto sources are not being
generated before hand and causing below compilation
failure:

hardware/ril/mock-ril/src/proto/ctrl.pb.h:26:52:
error: hardware/ril/mock-ril/src/proto/ril.pb.h: No such file or directory

This is due to ctrl.proto is importing ril.proto package
and dependency is only set on the ctrl header generated,
but, not on ril header.

Change-Id: I951deaaace432b3dba1934c588f7ff7047e5d764